spring:
  config:
    activate:
      on-profile: testdb
  jpa:
    show-sql: false
    # DB ??? ? ??? ??
    generate-ddl: true # DDL ??? ? ?? ??
    hibernate:
      ddl-auto: create   # DDL ???? ??
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
  datasource:
    url: jdbc:h2://~/jpatest
    username: sa
    password: password
  h2:
    console:
      path: /h2
      enabled: true

# Register P6LogFactory to log JDBC events
decorator.datasource.p6spy.enable-logging: true